export enum CustomFilterTypes {
    SITE_ID = 'Site ID',
    SWITCH_ID = 'Switch ID',
    RECORDER_ID = 'Recorder ID',
    COMPLETE_ID = 'Complete ID',
    INTERACTION_ID = 'Interaction ID',
    DIRECTION = 'Direction',
    AGENT_ID = 'Agent ID',
    AGENT_PHONE_NUMBER = 'Agent phone number',
    CUSTOM_PHONE_NUMBER = 'Customer phone number',
    DNIS_SEGMENT_DIALED_NUMBER = 'DNIS (Segment Dialed Number)',
    IN_LITIGATION_HOLD = 'In Litigation Hold',
    EXCEPTION_ID = 'Exception ID',
    EXCEPTION_DESCRIPTION = 'Exception Description',
    IN_PLAYBACK_LOCK = 'Playback Lock',
    NX_RECORDING_CONSENT_VIOLATION = 'NX_Recording-Consent-Violations-Category',
    NX_PRIVACY_DELETION = 'NX_Privacy-Deletion-Category',
    NX_SALES_CONSENT_VIOLATIONS = 'NX_Sales-Consent-Violations-Category',
    NX_SCRIPT_ADHERENCE_VIOLATIONS = 'NX_Script-Adherence-Violations-Category',
    NX_PCI_VIOLATIONS = 'NX_PCI-Violations',
    DURATION = 'Duration',
    SEGMENT_VECTOR_NUMBER = 'Segment Vector Number',
}